services:
  backend:
    build:
      context: .
      args:
        SPRING_PROFILE: dev
    container_name: svs-backend
    depends_on:
      - db
    ports:
      - "8081:8081"
    env_file:
      - .env.staging
    networks:
      - svs-net

  db:
    image: postgres:15
    container_name: svs-postgres
    restart: unless-stopped
    env_file:
      - .env.staging
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - svs-net

  adminer:
    image: adminer
    container_name: svs-adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - svs-net

volumes:
  pgdata:

networks:
  svs-net:
