spring:
  application:
    name: svs-backend

  # Configuration principale Spring
  main:
    allow-bean-definition-overriding: false
    banner-mode: console

  security:
    filter:
      disable: false

  # Configuration JPA commune
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        generate_statistics: false
        globally_quoted_identifiers: false
        use_sql_comments: false

  # Configuration Liquibase - DÉSACTIVÉ temporairement
  liquibase:
    enabled: false

  # Configuration des profils
  profiles:
    active: dev

# Configuration du serveur
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Configuration de base JWT
app:
  jwt:
    issuer: "svs-backend"
    # Les autres valeurs seront définies dans les profils spécifiques

  email:
    company-name: "Salane Vision S.a.r.l"
    company:
      address: "Zone Industrielle, Port Autonome de Dakar, Sénégal"
      phone: "+221 33 XXX XX XX"
      website: "https://www.salanevision.sn"
    signature:
      name: "L'équipe SVS Backoffice"
      title: "Service Informatique"

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /management
  endpoint:
    health:
      show-details: when_authorized
      roles: ''
      probes:
        enabled: true
  health:
    mail:
      enabled: false
  server:
    base-path: /management

# Configuration OpenAPI/Swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operationsSorter: method
    disable-swagger-default-url: true
    doc-expansion: none
    tags-sorter: alpha
  show-actuator: true
  group-configs:
    - group: 'svs-api'
      display-name: 'SVS API - Salane Vision S.a.r.l'
      paths-to-match: '/api/v1/**'