# Configuration pour les tests
spring:
  config:
    activate:
      on-profile: staging

  datasource:
    url: jdbc:postgresql://localhost:5432/staging_db
    username: staging_user
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: false

security:
  enabled: false

cors:
  allowed-origins: "*"

server:
  port: 8080